CREATE TABLE `hmda_lar` (
`loan_number` int(11) NOT NULL,
`app_date` varchar(8) NOT NULL,
`loan_type` int(11) NOT NULL,
`prop_type` int(11) NOT NULL,
`purpose` int(11) NOT NULL,
`occupancy` int(11) NOT NULL,
`amount` int(11) NOT NULL,
`preapproval` int(11) NOT NULL,
`action` int(11) NOT NULL,
`action_date` int(11) NOT NULL,
`msa` varchar(5) NOT NULL,
`state` varchar(2) NOT NULL,
`county` varchar(3) NOT NULL,
`census` varchar(10) NOT NULL,
`app_ethnicity` int(11) NOT NULL,
`coapp_ethnicity` int(11) NOT NULL,
`app_race1` int(11) NOT NULL,
`app_race2` int(11) DEFAULT NULL,
`app_race3` int(11) DEFAULT NULL,
`app_race4` int(11) DEFAULT NULL,
`app_race5` int(11) DEFAULT NULL,
`coapp_race1` int(11) NOT NULL,
`coapp_race2` int(11) DEFAULT NULL,
`coapp_race3` int(11) DEFAULT NULL,
`coapp_race4` int(11) DEFAULT NULL,
`coapp_race5` int(11) DEFAULT NULL,
`app_sex` int(11) NOT NULL,
`coapp_sex` int(11) NOT NULL,
`income` varchar(4) NOT NULL,
`purchaser_type` int(11) NOT NULL,
`denial_reason1` int(11) DEFAULT NULL,
`denial_reason2` int(11) DEFAULT NULL,
`denial_reason3` int(11) DEFAULT NULL,
`spread` varchar(5) NOT NULL,
`hoepa` int(11) NOT NULL,
`lien` int(11) NOT NULL,
`added` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`app_fname` varchar(50) DEFAULT NULL,
`app_lname` varchar(50) DEFAULT NULL,
`coapp_lname` varchar(50) DEFAULT NULL,
`coapp_fname` varchar(50) DEFAULT NULL,
`last_edited` timestamp NULL DEFAULT NULL,
`created_by` varchar(20) DEFAULT NULL,
`edited_by` varchar(20) DEFAULT NULL,
`checked` tinyint (1) DEFAULT NULL,
PRIMARY KEY (`loan_number`)
);

CREATE TABLE `incompletes` (
`loan_number` int(11) DEFAULT NULL,
`app_date` varchar(8) DEFAULT NULL,
`loan_type` int(11) DEFAULT NULL,
`prop_type` int(11) DEFAULT NULL,
`purpose` int(11) DEFAULT NULL,
`occupancy` int(11) DEFAULT NULL,
`amount` int(11) DEFAULT NULL,
`preapproval` int(11) DEFAULT NULL,
`action` int(11) DEFAULT NULL,
`action_date` int(11) DEFAULT NULL,
`msa` varchar(5) DEFAULT NULL,
`state` varchar(2) DEFAULT NULL,
`county` varchar(3) DEFAULT NULL,
`census` varchar(10) DEFAULT NULL,
`app_ethnicity` int(11) DEFAULT NULL,
`coapp_ethnicity` int(11) DEFAULT NULL,
`app_race1` int(11) DEFAULT NULL,
`app_race2` int(11) DEFAULT NULL,
`app_race3` int(11) DEFAULT NULL,
`app_race4` int(11) DEFAULT NULL,
`app_race5` int(11) DEFAULT NULL,
`coapp_race1` int(11) DEFAULT NULL,
`coapp_race2` int(11) DEFAULT NULL,
`coapp_race3` int(11) DEFAULT NULL,
`coapp_race4` int(11) DEFAULT NULL,
`coapp_race5` int(11) DEFAULT NULL,
`app_sex` int(11) DEFAULT NULL,
`coapp_sex` int(11) DEFAULT NULL,
`income` varchar(4) DEFAULT NULL,
`purchaser_type` int(11) DEFAULT NULL,
`denial_reason1` int(11) DEFAULT NULL,
`denial_reason2` int(11) DEFAULT NULL,
`denial_reason3` int(11) DEFAULT NULL,
`spread` varchar(5) DEFAULT NULL,
`hoepa` int(11) DEFAULT NULL,
`lien` int(11) DEFAULT NULL,
`added` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
`app_fname` varchar(50) DEFAULT NULL,
`app_lname` varchar(50) DEFAULT NULL,
`coapp_lname` varchar(50) DEFAULT NULL,
`coapp_fname` varchar(50) DEFAULT NULL,
`last_edited` timestamp NULL DEFAULT NULL,
`created_by` varchar(20) DEFAULT NULL,
`edited_by` varchar(20) DEFAULT NULL,
`checked` tinyint (1) DEFAULT NULL
);